using GovUk.Frontend.AspNetCore.ComponentGeneration;
using GovUk.Frontend.AspNetCore.Localization;
using GovUk.Frontend.AspNetCore.ModelBinding;
using GovUk.Frontend.AspNetCore.TagHelpers;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Razor;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.FileProviders;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Options;

namespace GovUk.Frontend.AspNetCore;

/// <summary>
/// Extension methods for setting up GovUk.Frontend.AspNetCore.
/// </summary>
public static class GovUkFrontendExtensions
{
    /// <summary>
    /// Adds GovUk.Frontend.AspNetCore services to the specified <see cref="IServiceCollection"/>.
    /// </summary>
    /// <param name="services">The <see cref="IServiceCollection" /> to add services to.</param>
    /// <returns>The <see cref="IServiceCollection"/> so that additional calls can be chained.</returns>
    public static IServiceCollection AddGovUkFrontend(this IServiceCollection services)
    {
        ArgumentNullException.ThrowIfNull(services);

        return AddGovUkFrontend(services, _ => { });
    }

    /// <summary>
    /// Adds GovUk.Frontend.AspNetCore services to the specified <see cref="IServiceCollection"/>.
    /// </summary>
    /// <param name="services">The <see cref="IServiceCollection" /> to add services to.</param>
    /// <param name="setupAction">An <see cref="Action{GovUkFrontendOptions}"/> to configure the provided <see cref="GovUkFrontendOptions"/>.</param>
    /// <returns>The <see cref="IServiceCollection"/> so that additional calls can be chained.</returns>
    public static IServiceCollection AddGovUkFrontend(
        this IServiceCollection services,
        Action<GovUkFrontendOptions> setupAction)
    {
        ArgumentNullException.ThrowIfNull(services);
        ArgumentNullException.ThrowIfNull(setupAction);

        services.AddMvcCore();

        services.TryAddSingleton<IGovUkFrontendLocalizer>(NullGovUkFrontendLocalizer.Instance);
        services.TryAddSingleton<IComponentGenerator>(sp =>
            new DefaultComponentGenerator(sp.GetRequiredService<IGovUkFrontendLocalizer>()));
        services.TryAddSingleton<IModelHelper, DefaultModelHelper>();
        services.AddSingleton<IConfigureOptions<MvcOptions>, ConfigureMvcOptions>();
        services.AddSingleton<IConfigureOptions<GovUkFrontendOptions>, ConfigureGovUkFrontendOptions>();
        services.AddTransient<PageTemplateHelper>();
        services.AddSingleton<ITagHelperInitializer<ButtonTagHelper>, ButtonTagHelperInitializer>();
        services.AddSingleton<ITagHelperInitializer<FileUploadTagHelper>, FileUploadTagHelperInitializer>();
        services.AddHttpContextAccessor();
        services.AddSingleton<VersionedAssetMiddleware>();

        services.Configure(setupAction);

        return services;
    }

    /// <summary>
    /// Localizes the content generated by GovUk.Frontend.AspNetCore using resources from <typeparamref name="TResourceSource"/>.
    /// </summary>
    /// <typeparam name="TResourceSource">The <see cref="Type"/> to use to locate the resources.</typeparam>
    /// <param name="services">The <see cref="IServiceCollection"/> to add services to.</param>
    /// <returns>The <see cref="IServiceCollection"/> so that additional calls can be chained.</returns>
    /// <remarks>
    /// The resources are looked up by the names defined on <see cref="GovUkFrontendResourceNames"/>.
    /// Names with no corresponding resource fall back to the library's built-in English content, so
    /// resource files need only contain the content that is being localized.
    /// </remarks>
    public static IServiceCollection AddGovUkFrontendLocalization<TResourceSource>(this IServiceCollection services)
    {
        ArgumentNullException.ThrowIfNull(services);

        return AddGovUkFrontendLocalization(
            services,
            sp => new StringLocalizerGovUkFrontendLocalizer(
                sp.GetRequiredService<IStringLocalizerFactory>().Create(typeof(TResourceSource))));
    }

    /// <summary>
    /// Localizes the content generated by GovUk.Frontend.AspNetCore using the resources with the specified
    /// base name and location.
    /// </summary>
    /// <param name="services">The <see cref="IServiceCollection"/> to add services to.</param>
    /// <param name="baseName">The base name of the resources.</param>
    /// <param name="location">The location of the resources; typically the name of the containing assembly.</param>
    /// <returns>The <see cref="IServiceCollection"/> so that additional calls can be chained.</returns>
    /// <remarks>
    /// The resources are looked up by the names defined on <see cref="GovUkFrontendResourceNames"/>.
    /// Names with no corresponding resource fall back to the library's built-in English content, so
    /// resource files need only contain the content that is being localized.
    /// </remarks>
    public static IServiceCollection AddGovUkFrontendLocalization(
        this IServiceCollection services,
        string baseName,
        string location)
    {
        ArgumentNullException.ThrowIfNull(services);
        ArgumentNullException.ThrowIfNull(baseName);
        ArgumentNullException.ThrowIfNull(location);

        return AddGovUkFrontendLocalization(
            services,
            sp => new StringLocalizerGovUkFrontendLocalizer(
                sp.GetRequiredService<IStringLocalizerFactory>().Create(baseName, location)));
    }

    /// <summary>
    /// Localizes the content generated by GovUk.Frontend.AspNetCore using the <see cref="IGovUkFrontendLocalizer"/>
    /// created by the specified factory.
    /// </summary>
    /// <param name="services">The <see cref="IServiceCollection"/> to add services to.</param>
    /// <param name="implementationFactory">The factory that creates the <see cref="IGovUkFrontendLocalizer"/>.</param>
    /// <returns>The <see cref="IServiceCollection"/> so that additional calls can be chained.</returns>
    public static IServiceCollection AddGovUkFrontendLocalization(
        this IServiceCollection services,
        Func<IServiceProvider, IGovUkFrontendLocalizer> implementationFactory)
    {
        ArgumentNullException.ThrowIfNull(services);
        ArgumentNullException.ThrowIfNull(implementationFactory);

        // ResourceManagerStringLocalizerFactory takes a dependency on ILoggerFactory.
        services.AddLogging();
        services.AddLocalization();

        // Replace rather than Add so that this works whether it's called before or after AddGovUkFrontend().
        services.Replace(ServiceDescriptor.Singleton(implementationFactory));

        return services;
    }

    /// <summary>
    /// Adds middleware to the request pipeline to handle the govuk-frontend assets.
    /// </summary>
    public static IApplicationBuilder UseGovUkFrontend(this IApplicationBuilder app)
    {
        ArgumentNullException.ThrowIfNull(app);

        var options = app.ApplicationServices.GetRequiredService<IOptions<GovUkFrontendOptions>>().Value;

        if (options.BuildInfo?.EnableGovUkFrontendSupport is true)
        {
            app.UseMiddleware<VersionedAssetMiddleware>();
        }

        if (options.FrontendPackageHostingOptions.HasFlag(FrontendPackageHostingOptions.HostAssets))
        {
            var fileProvider = new ManifestEmbeddedFileProvider(
                typeof(GovUkFrontendExtensions).Assembly,
                root: "Content/Assets");

            app.UseStaticFiles(new StaticFileOptions
            {
                FileProvider = fileProvider,
                RequestPath = PageTemplateHelper.DefaultAssetsPath,
                OnPrepareResponse = ctx =>
                {
                    var hasVersionQueryParam =
                        ctx.Context.Request.Query[HostCompiledAssetsMiddleware.StaticAssetVersionQueryParamName].Count != 0;

                    if (hasVersionQueryParam)
                    {
                        ctx.Context.Response.Headers.CacheControl = "Cache-Control: public, max-age=31536000, immutable";
                    }
                }
            });
        }

        if (options.FrontendPackageHostingOptions.HasFlag(FrontendPackageHostingOptions.HostCompiledFiles))
        {
            var fileProvider = new ManifestEmbeddedFileProvider(
                typeof(GovUkFrontendExtensions).Assembly,
                root: "Content/Compiled");

            app.UseMiddleware<HostCompiledAssetsMiddleware>(fileProvider);
        }

        return app;
    }

    private class ConfigureMvcOptions : IConfigureOptions<MvcOptions>
    {
        private readonly IOptions<GovUkFrontendOptions> _optionsAccessor;

        public ConfigureMvcOptions(IOptions<GovUkFrontendOptions> optionsAccessor)
        {
            ArgumentNullException.ThrowIfNull(optionsAccessor);

            _optionsAccessor = optionsAccessor;
        }

        public void Configure(MvcOptions options)
        {
            options.ModelBinderProviders.Insert(2, new DateInputModelBinderProvider(_optionsAccessor));
            options.ModelMetadataDetailsProviders.Add(new GovUkFrontendMetadataDetailsProvider());
        }
    }
}
