name: Setup tools

runs:
  using: composite

  steps:
    - run: sed -i '/^dotnet/d' mise.toml  # Remove dotnet from mise.toml
      shell: bash

    - uses: jdx/mise-action@v3

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          8.0.416
          9.0.314
          10.0.100

    - run: just install-tools
      shell: bash
