namespace GovUk.Frontend.AspNetCore.Localization;

/// <summary>
/// Provides localized content for the components and messages generated by this library.
/// </summary>
/// <remarks>
/// <para>
/// Implementations are resolved once and consumed by singleton services, so they must be thread-safe
/// and must derive the language from <see cref="System.Globalization.CultureInfo.CurrentUICulture"/>
/// on every call rather than caching it. Registering a scoped implementation will fail dependency
/// injection scope validation at startup.
/// </para>
/// <para>
/// Use <see cref="GovUkFrontendExtensions.AddGovUkFrontendLocalization{TResourceSource}(Microsoft.Extensions.DependencyInjection.IServiceCollection)"/>
/// to provide content from resource files rather than implementing this interface directly.
/// </para>
/// </remarks>
public interface IGovUkFrontendLocalizer
{
    /// <summary>
    /// Gets the localized content for the specified resource name.
    /// </summary>
    /// <param name="name">The resource name; one of the constants defined on <see cref="GovUkFrontendResourceNames"/>.</param>
    /// <returns>
    /// The localized content, or <see langword="null"/> to use the library's built-in English content.
    /// Returning <see langword="null"/> for an unrecognized name is always safe.
    /// </returns>
    string? GetString(string name);
}
